### ISSUE TITLE
Fluent msh format

### ISSUE THREAD

**Issue by JonasAparicio** [victorsndvg/FEconv#3]
Hello, 
Thank you for this much needed utility, is there any plan for supporting the fluent msh mesh in the future?
Jonas

**Comment by fran-pena** [comment]
Hello,

FEconv supports ANSYS mesh files (.msh). I believe this is the format you are requesting. Please, check the [ANSYS format help page](http://victorsndvg.github.io/FEconv/formats/ansysmsh.xhtml) to be sure.

Best,
Francisco

**Comment by JonasAparicio** [comment]
I find the issue, my mesh file was in a binary format, I saved it again in ASCII format and now. The conversion work.
Thank for your fast answer
Best
Jonas
